[tool.poetry]
name = "bsm2smeft"
version = "0.1.0"
description = ""
authors = ["Jorge-Alda <jorge.alda@pd.infn.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
wilson = "^2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
